// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_V1BC3TJ8haJLozaYnLOSTusPDW6DgU',
    appId: '1:870052428584:android:85f3cac7ece643ead56e1d',
    messagingSenderId: '870052428584',
    projectId: 'fooddeliver-90a2c',
    storageBucket: 'fooddeliver-90a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVr_Jl08cvlWFrjvAkOUK0CBxceecYRDw',
    appId: '1:870052428584:ios:f12b72fc0178d576d56e1d',
    messagingSenderId: '870052428584',
    projectId: 'fooddeliver-90a2c',
    storageBucket: 'fooddeliver-90a2c.appspot.com',
    androidClientId: '870052428584-563ip84j86s7ed2cr7cfjmpghctm11la.apps.googleusercontent.com',
    iosClientId: '870052428584-bqd87frku7b31lgufubv59ai7lft606b.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryapp',
  );
}
